<?php
//============================================================+
// File name   : example_006.php
// Begin       : 2008-03-04
// Last Update : 2013-05-14
//
// Description : Example 006 for TCPDF class
//               WriteHTML and RTL support
//
// Author: Nicola Asuni
//
// (c) Copyright:
//               Nicola Asuni
//               Tecnick.com LTD
//               www.tecnick.com
//               info@tecnick.com
//============================================================+


//dumper($img);

/**
 * Creates an example PDF TEST document using TCPDF
 * @package com.tecnick.tcpdf
 * @abstract TCPDF - Example: WriteHTML and RTL support
 * @author Nicola Asuni
 * @since 2008-03-04
 */
		
//dumper($form_request['created_at']);
// create new PDF document

$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$ns = str_replace("/","","");
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('PT. Infrastruktur Bisnis Sejahtera');
$pdf->SetTitle("HRIS-MDCR-".$header[0]->request_number);
$pdf->SetSubject("HRIS-MDCR".$header[0]->request_number);
$pdf->SetKeywords('HRIS-MDCR,IBS');

// set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE.' 006', PDF_HEADER_STRING);

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, "10", PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
//$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)

$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);
// ---------------------------------------------------------

// set font
$pdf->SetFont('Times', '', 11);

// writeHTML($html, $ln=true, $fill=false, $reseth=false, $cell=false, $align='')
// writeHTMLCell($w, $h, $x, $y, $html='', $border=0, $ln=0, $fill=0, $reseth=true, $align='', $autopadding=true)


// - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Print a table
$pdf->SetDisplayMode('fullpage', 'SinglePage', 'UseNone');
// add a page
$pdf->AddPage('P', 'LEGAL');

// $img = file_get_contents(base_url().'assets/v2/images/logo.png');
// $pdf->Image($img);

// create some HTML content
// $subtable = '<table border="0" cellspacing="6" cellpadding="4"><tr><td>a</td><td>b</td></tr><tr><td>c</td><td>d</td></tr></table>';
//<img height="80" src="'. base_url() .'assets/v2/images/logo_IBS.jpg">




if (!empty($additional)){
	if ($additional[0]['kuitansi'] == 'Asli') {
		$checked = 'checked';
	} else {
		$checked = '';
	}
	if ($additional[0]['resep'] == 1){
		$checked_r = 'checked';
	} else {
		$checked_r = '';
	}
}else{
	$checked 	= '';
	$checked_r 	= '';
}

//SPV
$file = '/assets/images/qrcode_mdcr/'.$header[0]->request_number.'-'.$header[0]->employee_id.'.png';

// if(is_writable($file)) {
//     $message = "The file $file exists";
// 	print_r($message);die;
// }else{
//     $message = "The file $file does not exist";
// 	print_r($message);die;
// }

//dumper($header);
//$header[0]->request_number.'-ApproveBySPR.png'

$diri_sendiri = "Diri Sendiri";

//dumper($tor);
if($tor == 'non_rawat_inap'){
	$qrcode_tor_spv = '';
}else{
	$qrcode_tor_spv = '<img height="60" src="/assets/images/qrcode_mdcr/'.$header[0]->request_number.'-ApprovedBySPR.png"><br><font size="8" align="center" valign="middle">Signature is generated by system.</font>';
}
//dumper($qrcode_tor_spv);

if(((decrypt($header[0]->employee_group)) == 'GOL B') || ((decrypt($header[0]->employee_group) == 'GOL C'))){
	$gol = "GOL B-C";
}else if(((decrypt($header[0]->employee_group)) == 'GOL D') || ((decrypt($header[0]->employee_group) == 'GOL E'))){
	$gol = "GOL D-E";
}else if(((decrypt($header[0]->employee_group)) == 'GOL F') || ((decrypt($header[0]->employee_group) == 'GOL G'))){
	$gol = "GOL F-G";
}else if(((decrypt($header[0]->employee_group)) == 'GOL H') || ((decrypt($header[0]->employee_group) == 'GOL I'))){
	$gol = "GOL H-I";
}else if(((decrypt($header[0]->employee_group)) == 'GOL J') || ((decrypt($header[0]->employee_group) == 'GOL K')) || ((decrypt($header[0]->employee_group) == 'GOL L'))){
	$gol = "GOL J-K-L";
}else if((decrypt($header[0]->employee_group)) == 'GOL A') {
	$gol = "GOL A";
}

$html = '
<table border="1" cellspacing="1" cellpadding="1" >
	<tr align="right" height="10px" bgcolor="#002060">
		<td width="20%" align="center">
			<img height="50" src="/assets/images/IBS.png">
		</td>
		<td colspan="2" width="60%" align="center">
			<br><br>
			<b><font color="white" font-family="arial">PERMOHONAN PENGGANTIAN BIAYA PENGOBATAN<br>
			<i>Medical Claim Form</i></font></b>
			<br>
		</td>
		<td width="20%" align="right">
			<b><font color="white" size="10">FH-HRG-016</font></b>
		</td>
	</tr>
	<tr align="left">
		<td>
		<font size="8">
			NAMA
			<br>
			<i>Name</i>
		</font>
		</td>
		<td>
		<font size="8">
		'. decrypt($header[0]->complete_name) .'
		</font>
		</td>
		<td>
		<font size="8">
			DEPARTEMEN / BAGIAN
			<br>
			<i>Department</i>
		</font>
		</td>
		<td>
		<font size="8">
		'. decrypt($header[0]->department) .'
		</font>
		</td>
	</tr>
	<tr align="left">
		<td>
		<font size="8">
			JABATAN/GOLONGAN
			<br>
			<i>Position</i>
		</font>
		</td>
		<td>
		<font size="8">
		'. decrypt($header[0]->position) .' / '. $gol .'
		</font>
		</td>
		<td>
		<font size="8">
			REGIONAL
			<br>
			<i>Region</i>
		</font>
		</td>
		<td>
		<font size="8">
		'. decrypt($header[0]->personnel_area) .'
		</font>
		</td>
	</tr>
	<tr align="left">
		<td>
		<font size="8">
			NO. KARYAWAN
			<br>
			<i>Employee ID number</i>
		</font>
		</td>
		<td colspan="3">
		<font size="8">
		'. ($header[0]->employee_id) .'
		</font>
		</td>
	</tr>
	<tr align="left">
		<td>
		<font size="8">
			NO. TELEPON
			<br>
			<i>Telephone number</i>
		</font>
		</td>
		<td colspan="3">
		<font size="8">
		'. decrypt($header[0]->phone_number) .'
		</font>
		</td>
	</tr>
</table>';
$html .= '
<table border="1" width="100%">
								<thead>
								  <tr align="center">
									<th width="5%">
									<font size="8">
										NO
									</font></th>
									<th width="35%">
									<font size="8">
										JENIS PENGGANTIAN
										<br>
										<i>Type of Reimbursement</i>
									</font></th>
									<th width="15%">
									<font size="8">
										JUMLAH KUITANSI  (lbr)
										<br>
										<i>Number of 
										Original Receipt</i>
									</font></th>
									<th width="15%">
									<font size="8">
										TOTAL NOMINAL KUITANSI (Rp)
										<br>
										<i>Total Amount of 
										Original Receipt</i>
									</font></th>
									<th width="15%">
									<font size="8">
										PENGGANTIAN (Rp)
										<br>
										<i>Reimbursement 
										(IDR)</i>
									</font>
									</th>
									<th width="15%">
									<font size="8">
										KETERANGAN
									</font>
									</th>
								  </tr>
								</thead>';
		$no=0;
		foreach($detail as $la){
		$no++;
		if ( ($la->additional == 'Diri Sendiri') ){
			$additional = $la->additional;
		}else{
			$additional = ucwords(decrypt((strtolower($la->additional))));
		}
$html .= '
		<tbody>
		  <tr align="center">
		  <td width="5%"><font size="8">'.$no.'</font></td>
		  <td width="35%"><font size="8">'.$la->tor_grandparent.' / '.$la->tor_parent.' / '.$la->tor_child.'</font></td>
		  <td width="15%"><font size="8">'.$la->jumlah_kuitansi.'</font></td>
		  <td width="15%"><font size="8">'.number_format($la->total_kuitansi).'</font></td>
		  <td width="15%"><font size="8">'.number_format($la->penggantian).'</font></td>
		  <td width="15%"><font size="8">'.$la->keterangan.' - '.$additional.'</font></td>
		  </tr> 
		</tbody>	
';
		};

//dumper($detail);

$html .= '</table>
<table border="1">
	<tr>
		<td colspan="2" width="40%">
			<font size="8" align="center">
				<b>TOTAL</b>
			</font>
		</td>
		<td width="15%" align="center">
			
		</td>
		<td width="15%" align="center">
			
		</td>
		<td width="15%" align="center">
			<font size="8" align="center">
				'. number_format(($sum_penggantian_jalan[0]->sum_penggantian) + ($sum_penggantian_inap[0]->sum_penggantian) + ($sum_penggantian_kacamata[0]->sum_one_focus) + ($sum_penggantian_kacamata[0]->sum_two_focus) + ($sum_penggantian_kacamata[0]->sum_frame)) .'
			</font>
		</td>
		<td width="15%" rules="none" rowspan="2" align="middle">
		
		</td>
	</tr>
	<tr>
		<td colspan="4" width="70%">
			<font size="8" align="left">
				POTONGAN (kelebihan atas Jatah Tahunan)<br>
				<i>Deduction (over limit from current years entitlement)</i>
			</font>
		</td>
		<td width="15%" align="center">
			-
		</td>
	</tr>
	<tr>
		<td colspan="4" width="70%">
			<font size="8" align="left">
				TOTAL PENGGANTIAN YANG DISETUJUI<br>
				<i>Total Approved Reimbursement</i>
			</font>
		</td>
		<td width="15%" align="center">
			<font size="8" align="center">
				'. number_format(($sum_penggantian_jalan[0]->sum_penggantian) + ($sum_penggantian_inap[0]->sum_penggantian) + ($sum_penggantian_kacamata[0]->sum_one_focus) + ($sum_penggantian_kacamata[0]->sum_two_focus) + ($sum_penggantian_kacamata[0]->sum_frame)) .'
			</font>
		</td>
		<td width="15%" rowspan="5" rowspan="0" align="center">
		';
	if($form_request['is_status_admin_hr'] == 1){
		$html .='<font size="8" align="center"><b>Checked By HR Support</b></font>';
	}
$html .='
		</td>
	</tr>
	<tr>
		<td rowspan="2" colspan="3" width="40%"  align="left" valign="middle">
			<font size="8">
				SISA BIAYA PENGOBATAN<br>
				<i>Remaining Reimbursement Limit</i>
			</font>
		</td>
		<td width="30%" colspan="2" align="center">
		<font size="8" align="left" valign="middle">
			Rawat jalan<br>
			<i>Out-patient<br>Effective date : '.$form_request['created_at'].'</i>
		</font>
		</td>
		<td width="15%" align="center">
			<font size="8" align="center">
				'.number_format($data_total_claim['balancing_jalan_tahun']).'
			</font>
		</td>
	</tr>
	<tr>
		<td width="30%" colspan="2" align="center">
		<font size="8" align="left" valign="middle">
			Rawat inap<br>
			<i>In-patient<br>Effective date : '.$form_request['created_at'].'</i>
		</font>
		</td>
		<td width="15%" align="center">
			<font size="8" align="center">
				'.number_format($data_total_claim['balancing_inap_tahun']).'
			</font>
		</td>
	</tr>
	<tr>
		<td rowspan="2" colspan="3" width="40%"  align="left" valign="middle">
			<font size="8">
				BUKTI-BUKTI YANG DILAMPIRKAN<br>
				<i>Submitted original receipt</i>
			</font>
		</td>
		<td width="60%" colspan="3" align="left">
		<input type="checkbox" name="box" value="1" checked="'.$checked.'" readonly="true" />
		<font size="8" align="left" valign="middle">
			Kuitansi asli (Dokter, Apotik, Rumah Sakit, Klinik, Laboratorium)<br>
			<i>Original receipt (doctor, pharmacist, hospital, clinic, laboratory)</i>
		</font>
		</td>
	</tr>
	<tr>
		<td width="60%" colspan="3" align="left">
		<input type="checkbox" name="box" value="1" checked="'.$checked_r.'" readonly="true" />
		<font size="8" align="left" valign="middle">
			Copy Resep Dokter<br>
			<i>Copy of Medical Prescription</i>
		</font>
		</td>
	</tr>
	<tr>
		<td width="40%" rowspan="2" colspan="2" align="left">
		<font size="8" align="left" valign="middle">
			DIAGNOSA
		</font>
		</td>
		<td width="60%" rowspan="2" colspan="4" align="left">
		<font size="8" align="left" valign="middle">';

		for($x=0;$x<count($listToR);$x++){
			$html .= ' - '.$listToR[$x]->diagnosa.' / ';
		};

$html .='
		</font>
		</td>
	</tr>
	<tr>
		<td>
		</td>
		<td>
		</td>
	</tr>
	<tr>
		<td width="34%" colspan="3" align="center">
		<font size="8" align="center" valign="middle">
			DIBUAT OLEH PEMOHON <br>
			<i>Prepared by Requestor</i>
		</font>
		</td>
		<td width="33%" colspan="3" align="center">
		<font size="8" align="center" valign="middle">
			DIKETAHUI OLEH ATASAN<br>
			<i>Acknowledged by Superior</i><br>
			*apabila rawat inap
		</font>
		</td>
		<td width="33%" colspan="3" align="center">
		<font size="8" align="center" valign="middle">
			DISETUJUI OLEH HR<br>
			<i>Approved by HR</i>
		</font>
		</td>
	</tr>
	<tr>';
	if(($header[0]->is_status == 3)){
		$html .='
		<td width="34%" colspan="3" align="center">
			<img height="60" src="/assets/images/qrcode_mdcr/'.$header[0]->request_number.'-'.$header[0]->employee_id.'.png"><br>
			<font size="8" align="center" valign="middle">Signature is generated by system.</font>
		</td>
		<td width="33%" colspan="3" align="center">
			'.$qrcode_tor_spv.'
		</td>
		<td width="33%" colspan="3" align="center">
			<img height="60" src="/assets/images/qrcode_mdcr/'.$header[0]->request_number.'-ApprovedByHR.png"><br>
			<font size="8" align="center" valign="middle">Signature is generated by system.</font>
		</td>';
	}else if(($header[0]->is_status_admin_hr == 1)){
		$html .='<td width="34%" colspan="3" align="center">
		<img height="60" src="/assets/images/qrcode_mdcr/'.$header[0]->request_number.'-'.$header[0]->employee_id.'.png"><br>
		<font size="8" align="center" valign="middle">Signature is generated by system.</font>
	</td>
	<td width="33%" colspan="3" align="center">
		'.$qrcode_tor_spv.'
	</td>
	<td width="33%" colspan="3" align="center">
	</td>';
	}else{
		$html .='<td width="34%" colspan="3" align="center">
		<img height="60" src="/assets/images/qrcode_mdcr/'.$header[0]->request_number.'-'.$header[0]->employee_id.'.png"><br>
		<font size="8" align="center" valign="middle">Signature is generated by system.</font>
	</td>
	<td width="33%" colspan="3" align="center">
	</td>
	<td width="33%" colspan="3" align="center">
	</td>';
	}
	$html .='</tr>
	<tr>
		<td width="10%" colspan="2" align="left">
		<font size="8" align="left" valign="middle">
			Nama <br>
			<i>Name</i>
		</font>
		</td>
		<td width="24%" colspan="1" align="center">
		<font size="8" align="center" valign="middle">
		'. decrypt($header[0]->complete_name) .'
		</font>
		</td>
		<td width="33%" colspan="3" align="center">
		<font size="8" align="center" valign="middle">
		';

		if(($tor == 'rawat_inap') && ($header[0]->is_status == 3)){
			$html .= ''.decrypt($approver[0]->complete_name);
			// $html .= 'hehe';
		} else if(($tor == 'rawat_inap') && ($header[0]->is_status_admin_hr == 1)){
			$html .= ''.decrypt($approver[0]->complete_name);
		};

$html .='
		</font>
		</td>
		<td width="33%" colspan="3" align="center">
		<font size="8" align="center" valign="middle">
		';
		// dumper(decrypt($approver[2]->complete_name));
		// dumper($approver[1]);
		if(($tor == 'rawat_inap') && ($header[0]->is_status == 3)){
			$html .= ''.decrypt($approver[2]->complete_name);
		}else if(($header[0]->is_status == 3)){
			// $html .= ''.decrypt($approver[0]->complete_name);
			$html .= ''.decrypt($approver[1]->complete_name);
		};

$html .='
		</font>
		</td>
	</tr>
	<tr>
		<td width="10%" colspan="2" align="left">
		<font size="8" align="left" valign="middle">
			Jabatan <br>
			<i>Title</i>
		</font>
		</td>
		<td width="24%" colspan="1" align="center">
		<font size="8" align="center" valign="middle">
		'. decrypt($header[0]->position) .'
		</font>
		</td>
		<td width="33%" colspan="3" align="center">
		<font size="8" align="center" valign="middle">
		';
		
		if(($tor == 'rawat_inap') && ($header[0]->is_status == 3)){
			$html .= ''.decrypt($approver[0]->position);
		} else if(($tor == 'rawat_inap') && ($header[0]->is_status_admin_hr == 1)){
			$html .= ''.decrypt($approver[0]->position);
		};
		
$html .='
		</font>
		</td>
		<td width="33%" colspan="3" align="center">
		<font size="8" align="center" valign="middle">
		';
		
		if(($tor == 'rawat_inap') && ($header[0]->is_status == 3)){
			$html .= ''.decrypt($approver[2]->position);
		}else if(($header[0]->is_status == 3)){
			// $html .= ''.decrypt($approver[0]->position);
			$html .= ''.decrypt($approver[1]->position);
		};
		
	if ($header[0]->revise != null) {
		$upd = '			<font size="8" align="center" valign="middle">'.$header[0]->created_at.'</font><br>
			<font size="8" align="center" valign="middle">'.$header[0]->updated_at.' (Rev.)</font>';
	} else {
		$upd = '			<font size="8" align="center" valign="middle">'.$header[0]->created_at.'</font><br>';
	}
	


$html .='
		</font>
		</td>
	</tr>
	<tr>
		<td width="10%" colspan="2" align="left">
		<font size="8" align="left" valign="middle">
			Tanggal <br>
			<i>Date</i>
		</font>
		</td>
		<td width="24%" colspan="1" align="center">
		'.$upd.'
		</td>
		<td width="33%" colspan="3" align="center">
		<font size="8" align="center" valign="middle">
		';
		
		if(($tor == 'rawat_inap') && ($header[0]->is_status == 3)){
			$html .= ''.$approver[0]->approval_date;
		} else if(($tor == 'rawat_inap') && ($header[0]->is_status_admin_hr == 1)){
			$html .= ''.$approver[0]->approval_date;
		};
		
$html .='
		</font>
		</td>
		<td width="33%" colspan="3" align="center">
		<font size="8" align="center" valign="middle">
		';
		
		if(($tor == 'rawat_inap') && ($header[0]->is_status == 3)){
			$html .= ''.$approver[2]->approval_date;
		}else if(($header[0]->is_status == 3)){
			// $html .= ''.$approver[0]->approval_date;
			$html .= ''.$approver[1]->approval_date;
		};
		
$html .='
		</font>
		</td>
	</tr>

</table>
<table border="1" cellspacing="2" cellpadding="4">
	<tr>
		<td>
		<font size="8">
		<p align="justify">
		Semua KUITANSI pengobatan sudah harus diajukan untuk permohonan penggantian biaya selambat-lambatnya 30 hari sejak tanggal penerbitan kuitansi tersebut. KUITANSI dengan tanggal pengeluaran lebih dari 1 (satu) bulan pada tanggal pengajuan dianggap kadaluarsa & tidak berhak atas penggantian biaya (sesuai dengan Kebijakan/Prosedur yang berlaku).
		All medical receipt must be submitted for reimbursement no less than 30 days from the issuance date of the medical receipt. Medical receipt with an issuance date more than 1 (one) month to submission date will be considered expired and no longer valid to be reimbursed (refer to Policy/Procedure).
		</p>
		</font>
		</td>
	</tr>
	<tr>
	<td width="15%"><font size="8"><b>Effective Date</b></font></td>
	<td width="15%"><font size="8"><b>06-Jan-20</b></font></td>
	<td width="15%"><font size="8"><b>Revision History</b></font></td>
	<td width="15%"><font size="8"><b>Rev. 02</b></font></td>
	<td width="38.5%"><font size="8"><b>'.$no_req_mdcr.' | '.$form_request['no_req_mdcr'].'</b></font></td>
	</tr>
</table>
';
// $html = $nosurat;
// output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// ---------------------------------------------------------

//Close and output PDF document
$pdf->Output($ns, 'I');
//============================================================+
// END OF FILE
//============================================================+